### ISSUE TITLE
Check in Dockerfile to build Zeppelin test container.

### ISSUE THREAD

**Issue by jasoncwik** [EMCECS/spark-ecs-s3#6]
Please check in the Dockerfile used to generate the test container with Zeppelin

**Comment by EronWright** [comment]
Have a look at the 'demo' branch, it has the Dockerfile that I used.    I don't have an opinion on how to integrate the demo code into master.

**Comment by EronWright** [comment]
I don't think we need to provide a bundled Zeppelin demo environment, at least not in this repository.  Re-open if you disagree.
